# Generated by Django 3.2.7 on 2021-10-21 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("problems", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="problem",
            old_name="description",
            new_name="note",
        ),
        migrations.AddField(
            model_name="problem",
            name="max_score",
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
