# Generated by Django 3.2.7 on 2021-11-01 08:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('problems', '0003_submission'),
    ]

    operations = [
        migrations.RenameField(
            model_name='submission',
            old_name='created_by',
            new_name='created_By',
        ),
        migrations.RenameField(
            model_name='submission',
            old_name='problemId',
            new_name='problem_Id',
        ),
    ]
