# Generated by Django 3.2.7 on 2021-11-02 13:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('problems', '0005_auto_20211102_1228'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='submission',
            name='input_Given',
        ),
        migrations.RemoveField(
            model_name='submission',
            name='output_Generated',
        ),
    ]
