# Generated by Django 3.2.7 on 2021-11-02 15:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("problems", "0006_auto_20211102_1903"),
    ]

    operations = [
        migrations.DeleteModel(
            name="UploadTC",
        ),
    ]
