# Generated by Django 3.2.7 on 2022-02-02 12:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('problems', '0014_auto_20220123_1244'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProblemMedia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('media_type', models.CharField(blank=True, default='image', max_length=20, null=True)),
                ('public_id', models.CharField(blank=True, max_length=200, null=True)),
                ('problem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='problems.problem')),
            ],
        ),
    ]
