# Generated by Django 3.2.7 on 2022-02-02 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('problems', '0015_problemmedia'),
    ]

    operations = [
        migrations.AddField(
            model_name='problem',
            name='public_ids',
            field=models.TextField(blank=True, null=True),
        ),
    ]
