# Generated by Django 3.2.7 on 2022-02-02 16:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('problems', '0016_problem_public_ids'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='problem',
            name='public_ids',
        ),
    ]
