version: "3.8"

services:
  code_web:
    build: .
    container_name: code_web
    command: >
      sh -c "python3 manage.py wait_for_db &&
             gunicorn runcode.wsgi:application --bind 0.0.0.0:8000"
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    environment:
      - DB_HOST=code_db
      - DB_NAME=code
      - DB_USER=server
      - DB_PASSWORD=server
    depends_on:
      - code_db
      - redis
  daphne:
    build: .
    command: "daphne runcode.asgi:application --bind 0.0.0.0 --port 8001"
    volumes:
      - .:/app
    ports:
      - "8001:8001"
    depends_on:
      - code_db
      - redis
      - celery
  redis:
    image: redis:3.2
    command: redis-server
    ports:
      - "6379:6379"
  celery:
    build: .
    command: celery -A runcode.celery worker -l INFO
    volumes:
      - .:/app
    depends_on:
      - code_web
      - redis
  code_db:
    image: postgres
    container_name: code_db
    environment:
      - POSTGRES_DB=code
      - POSTGRES_USER=server
      - POSTGRES_PASSWORD=server
    volumes:
      - pgdata:/var/lib/postgresql/data/
    ports:
      - "5432:5432"
volumes:
  pgdata:
