version: "3.8"

networks:
  dirtybits:
    name: dirtybits
    driver: bridge
    attachable: false

services:
  code_web:
    build: .
    container_name: code_web
    command: >
      sh -c "python3 manage.py wait_for_db &&
             gunicorn runcode.wsgi:application --bind 0.0.0.0:8000"
    volumes:
      - .:/app
    env_file:
      - .env
    depends_on:
      - code_db
      - redis
    networks:
      - dirtybits
  daphne:
    build: .
    command: "daphne runcode.asgi:application --bind 0.0.0.0 --port 8001"
    volumes:
      - .:/app
    env_file:
      - .env
    depends_on:
      - code_db
      - redis
      - celery
    networks:
      - dirtybits
  redis:
    image: redis
    command: redis-server
    volumes:
      - .:/app
    networks:
      - dirtybits
  celery:
    build: .
    command: celery -A runcode.celery worker -l debug
    volumes:
      - .:/app
    env_file:
      - .env
    depends_on:
      - code_web
      - code_db
      - redis
    networks:
      - dirtybits
  code_db:
    image: postgres
    container_name: code_db
    env_file:
      - .env
    volumes:
      - pgdata:/var/lib/postgresql/data/
    networks:
      - dirtybits
  nginx:
    image: nginx
    networks:
      - dirtybits
    volumes:
      - ./nginx:/etc/nginx/conf.d
      - ./static:/static
    ports:
      - "8080:80"
    depends_on:
      - celery
      - redis
      - daphne
      - code_web
volumes:
  pgdata:
